---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    driver_config:
      box: Win2k12R2Core
      box_url: file:///Users/cbbohano/vagrant-boxes/win2012core/Win2k12R2Core_C_D.box

suites:
  - name: default
    run_list:
     - recipe[hello::default]
